import { test, after } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parsePrompt } from "../../lib/prompt-engine/parser.mjs";
import { conservativeRewriteCandidates, candidatePatch, mergeTexts, MERGE_SIMILARITY_FLOOR } from "../../lib/prompt-engine/rewrite-adapter.mjs";
import { semanticCandidates } from "../../lib/prompt-engine/optimizer.mjs";
import { applyPatch } from "../../lib/prompt-engine/patch.mjs";
import { PromptLabStore } from "../../lib/prompt-lab/store.mjs";
import * as API from "../../lib/prompt-lab/api.mjs";

const tmp = mkdtempSync(join(tmpdir(), "pl-rewrite-"));
const openStores = [];
after(() => {
	for (const s of openStores) {
		try {
			s.close();
		} catch {
			/* ignore */
		}
	}
	rmSync(tmp, { recursive: true, force: true });
});
const fresh = (n) => {
	const s = PromptLabStore.open(join(tmp, `${n}.db`));
	openStores.push(s);
	return s;
};

const NEAR_MD =
	"# Rules\n\n- Deterministic ordering before every request.\n- Keep the user request last.\n\n# Rules\n\n- Deterministic ordering before every request.\n- Keep the user request last, always.\n\n# User\n\nplease do the thing";

test("rewrite-adapter: near-dup rule sections yield a SEMANTIC MERGE candidate", () => {
	const m = parsePrompt(NEAR_MD, { sourceType: "markdown" });
	const cands = conservativeRewriteCandidates(m);
	assert.equal(cands.length, 1);
	const c = cands[0];
	assert.equal(c.risk, "SEMANTIC_REWRITE");
	assert.equal(c.requiresEval, true);
	assert.equal(c.ops.length, 1);
	assert.equal(c.ops[0].type, "MERGE_BLOCKS");
	assert.ok(c.tokenDelta < 0, "merge saves tokens");
	// applying the candidate patch preserves both rule lines + the user block
	const patch = candidatePatch(m, c);
	const r = applyPatch(m, patch, { onStale: "return" });
	assert.equal(r.ok, true);
	const text = r.manifest.blocks.map((b) => b.text).join("\n");
	assert.ok(text.includes("Deterministic ordering") && text.includes("Keep the user request last"));
	assert.ok(text.includes("please do the thing"));
	assert.equal(r.manifest.blocks.length, 2, "two rule sections merged into one");
});

test("rewrite-adapter: exact duplicates are NOT semantic candidates (Mode B owns them)", () => {
	const m = parsePrompt("# Rules\n\n- a\n- b\n\n# Rules\n\n- a\n- b\n", { sourceType: "markdown" });
	assert.equal(conservativeRewriteCandidates(m).length, 0);
});

test("rewrite-adapter: mergeTexts unions distinct lines first-seen", () => {
	const out = mergeTexts("line a\nline b", "line b\nline c");
	assert.deepEqual(out.split("\n"), ["line a", "line b", "line c"]);
	assert.ok(MERGE_SIMILARITY_FLOOR > 0.5 && MERGE_SIMILARITY_FLOOR < 1);
});

test("optimizer: Mode-C pendingEval candidates carry executable ops", () => {
	const m = parsePrompt(NEAR_MD, { sourceType: "markdown" });
	const cands = semanticCandidates(m);
	assert.ok(cands.length >= 1);
	for (const c of cands) assert.ok(Array.isArray(c.ops) && c.ops.length >= 1, "candidate carries ops");
});

test("api: semantic confirm requires Eval evidence first (P10), then applies", () => {
	const s = fresh("gate");
	const o = API.routeOptimize(s, { content: NEAR_MD, sourceType: "markdown", mode: "C" });
	assert.ok(o.pendingEval.length >= 1);
	// without Eval → blocked
	const blocked = API.routeConfirmSemantic(s, { versionId: o.version.versionId });
	assert.equal(blocked.ok, false);
	assert.match(blocked.error, /P10/);
	// run Eval, then confirm works and is undoable
	const ev = API.routeEvaluate(s, { content: NEAR_MD, sourceType: "markdown" });
	assert.equal(ev.ok, true);
	const conf = API.routeConfirmSemantic(s, { versionId: o.version.versionId });
	assert.equal(conf.ok, true, conf.error ?? "");
	assert.equal(conf.risk, "SEMANTIC_REWRITE");
	const undo = API.routePatchReverse(s, { versionId: conf.childVersionId });
	assert.equal(undo.ok, true);
});

test("api: export Step-11 targets (agents/claude/rules/skill/openai/anthropic)", () => {
	const e = (t) => API.routeExport(null, { content: NEAR_MD, sourceType: "markdown", format: "file", target: t });
	const agents = e("AGENTS");
	assert.equal(agents.ok, true);
	assert.equal(agents.filename, "AGENTS.md");
	assert.match(agents.text, /generated by Token-Mind/);
	assert.equal(e("CLAUDE").filename, "CLAUDE.md");
	assert.equal(e("RULES").filename, ".cursor/rules/prompt-lab.mdc");
	assert.equal(e("SKILL").filename, "SKILL.md");
	assert.equal(e("BOGUS").ok, false);
	const oai = API.routeExport(null, { content: NEAR_MD, sourceType: "markdown", format: "openai_json" });
	assert.equal(oai.ok, true);
	assert.ok(Array.isArray(oai.json));
	const ant = API.routeExport(null, { content: NEAR_MD, sourceType: "markdown", format: "anthropic_json" });
	assert.equal(ant.ok, true);
	assert.ok(typeof ant.json === "object" && ant.json.system !== undefined);
});
